name: Publish Artifacts

on:
  release:
    types:
      - published

jobs:
  Build-Forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew -p neoforge build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: neoforge/build/libs/!(*-@(dev|sources|api|javadoc)).jar
          github-files: neoforge/build/libs/*-@(dev|sources|api|javadoc).jar
          version-type: release
          game-versions: 1.20.1
          game-version-filter: releases
          modrinth-featured: true
          modrinth-id: TdqNMhOn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1241121
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: |
            neoforge
            forge
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
  Build-Fabric:
    runs-on: ubuntu-latest
    needs: [Build-Forge] # So that fabric is always the latest on modrinth & curseforge
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew -p fabric build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: fabric/build/libs/!(*-@(dev|sources|api|javadoc)).jar
          github-files: fabric/build/libs/*-@(dev|sources|api|javadoc).jar
          version-type: release
          game-versions: |
            1.20.1
          game-version-filter: releases
          modrinth-featured: true
          modrinth-id: TdqNMhOn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1241121
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: |
            fabric
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip